export const AUDIT_PERMISSIONS = {
  // Taxpayer
  AUDIT_VIEW_OWN:        'AUDIT_VIEW_OWN',
  AUDIT_UPLOAD_DOCUMENT: 'AUDIT_UPLOAD_DOCUMENT',
  AUDIT_RESPOND:         'AUDIT_RESPOND',
  AUDIT_VIEW_ORDER:      'AUDIT_VIEW_ORDER',

  // Audit Officer
  AUDIT_CREATE:           'AUDIT_CREATE',
  AUDIT_VIEW_ALL:         'AUDIT_VIEW_ALL',
  AUDIT_REQUEST_DOCUMENT: 'AUDIT_REQUEST_DOCUMENT',
  AUDIT_ADD_FINDING:      'AUDIT_ADD_FINDING',
  AUDIT_PROPOSE_ASSESSMENT: 'AUDIT_PROPOSE_ASSESSMENT',

  // Supervisor
  AUDIT_APPROVE_ASSESSMENT: 'AUDIT_APPROVE_ASSESSMENT',
  AUDIT_CLOSE:              'AUDIT_CLOSE',
  AUDIT_REASSIGN:           'AUDIT_REASSIGN',

  // Admin
  AUDIT_FULL_ACCESS: 'AUDIT_FULL_ACCESS',
} as const;

export type AuditPermission = typeof AUDIT_PERMISSIONS[keyof typeof AUDIT_PERMISSIONS];

